"""Local WS connectivity check using configs generated by generation-smoke.sh.

Usage: python tests/ws-egress-smoke.py OFFICIAL_SING_BOX CONFIG_DIR
Requires curl; does not claim VPS, systemd, Nginx or Cloudflare verification.
"""
import copy
import http.server
import json
import pathlib
import socket
import struct
import subprocess
import sys
import threading
import time

core, directory = sys.argv[1], pathlib.Path(sys.argv[2])
processes, servers = [], []
dns_socket = None


def free_port():
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def wait_port(port, process):
    for _ in range(100):
        if process.poll() is not None:
            raise RuntimeError(f"core exited: {process.returncode}")
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=0.1):
                return
        except OSError:
            time.sleep(0.05)
    raise RuntimeError(f"port {port} not ready")


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        body = b"IPv6" if ":" in self.client_address[0] else b"IPv4"
        self.send_response(200)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *args):
        pass


class IPv6Server(http.server.ThreadingHTTPServer):
    address_family = socket.AF_INET6


def serve_dns(sock):
    # Controlled A/AAAA replies exercise both preferences without host DNS edits.
    while True:
        try:
            data, address = sock.recvfrom(4096)
        except OSError:
            return
        offset = 12
        while data[offset]:
            offset += data[offset] + 1
        offset += 1
        kind = struct.unpack("!H", data[offset:offset + 2])[0]
        question = data[12:offset + 4]
        value = socket.inet_pton(socket.AF_INET if kind == 1 else socket.AF_INET6,
                                 "127.0.0.1" if kind == 1 else "::1") if kind in (1, 28) else b""
        answer = b"\xc0\x0c" + struct.pack("!HHIH", kind, 1, 60, len(value)) + value if value else b""
        response = data[:2] + struct.pack("!HHHHH", 0x8180, 1, bool(value), 0, 0) + question + answer
        sock.sendto(response, address)


try:
    http4 = http.server.ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    servers.append(http4)
    port = http4.server_port
    http6 = IPv6Server(("::1", port), Handler)
    servers.append(http6)
    for server in servers:
        threading.Thread(target=server.serve_forever, daemon=True).start()
    server_config = json.loads((directory / "server.json").read_text())
    dns_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    dns_socket.bind(("127.0.0.1", 0))
    threading.Thread(target=serve_dns, args=(dns_socket,), daemon=True).start()
    server_config["dns"]["servers"] = [{"type": "udp", "tag": "local", "server": "127.0.0.1",
                                        "server_port": dns_socket.getsockname()[1]}]
    # WARP is external; this smoke checks direct and the per-node SOCKS path.
    server_config["route"]["rules"] = [
        r for r in server_config["route"]["rules"] if r.get("outbound") != "warp"
    ]
    server_config["outbounds"] = [o for o in server_config["outbounds"] if o["tag"] != "warp"]
    server_config["experimental"]["clash_api"]["external_controller"] = f"127.0.0.1:{free_port()}"
    hop_port = free_port()
    server_config["inbounds"].append({
        "type": "socks", "tag": "proxy-hop", "listen": "127.0.0.1",
        "listen_port": hop_port, "users": [{"username": "user", "password": "pass"}],
    })
    for outbound in server_config["outbounds"]:
        if outbound["tag"] == "socks-Proxy":
            outbound.update(server="127.0.0.1", server_port=hop_port)
    for inbound in server_config["inbounds"]:
        if inbound["type"] != "socks":
            inbound["listen_port"] = free_port()
    path = directory / "ws-server.json"
    path.write_text(json.dumps(server_config), encoding="utf-8")
    log = (directory / "ws-server.log").open("w", encoding="utf-8")
    process = subprocess.Popen([core, "run", "-c", str(path)], stdout=log, stderr=log)
    processes.append((process, log))
    wait_port(hop_port, process)
    client_template = json.loads((directory / "client.json").read_text())
    for index, outbound in enumerate(client_template["outbounds"]):
        outbound = copy.deepcopy(outbound)
        inbound = server_config["inbounds"][index]
        outbound.update(server="127.0.0.1", server_port=inbound["listen_port"])
        outbound.pop("tls", None)
        socks_port = free_port()
        client = {"inbounds": [{"type": "socks", "tag": "client", "listen": "127.0.0.1", "listen_port": socks_port}],
                  "outbounds": [outbound], "route": {"final": outbound["tag"]}}
        path = directory / f"ws-client-{index}.json"
        path.write_text(json.dumps(client), encoding="utf-8")
        log = (directory / f"ws-client-{index}.log").open("w", encoding="utf-8")
        process = subprocess.Popen([core, "run", "-c", str(path)], stdout=log, stderr=log)
        processes.append((process, log))
        wait_port(socks_port, process)
        for host, expected in [("127.0.0.1", "IPv4"), ("[::1]", "IPv6"),
                               ("egress.test", "IPv6" if index == 1 else "IPv4")]:
            result = subprocess.run(["curl", "-fsS", "--noproxy", "", "--max-time", "10",
                                     "--socks5-hostname", f"127.0.0.1:{socks_port}",
                                     f"http://{host}:{port}/"], capture_output=True, text=True, check=True)
            assert result.stdout == expected, (outbound["type"], host, result.stdout, expected)
        print(f"{outbound['type'].upper()}_WS_IPV4_IPV6_OK")
    print("WS_EGRESS_SMOKE_OK")
finally:
    for process, log in reversed(processes):
        process.terminate()
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
        log.close()
    for server in servers:
        server.shutdown()
        server.server_close()
    if dns_socket:
        dns_socket.close()
